# Generated by Django 3.0.6 on 2020-05-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaCita', models.TimeField()),
                ('fechaCita', models.DateField()),
                ('medico', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('unidadAtencion', models.CharField(max_length=100)),
                ('IDPaciente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
